# Generated by Django 5.2.5 on 2025-09-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('experience_type', models.CharField(choices=[('newcomer', '신입'), ('experienced', '경력')], max_length=20, verbose_name='신입/경력')),
                ('is_attending', models.BooleanField(default=False, verbose_name='재직중 여부')),
                ('start_date', models.DateField(verbose_name='입사일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='부서')),
                ('responsibilities', models.TextField(blank=True, verbose_name='담당 업무')),
                ('reason_for_leaving', models.CharField(blank=True, max_length=255, verbose_name='퇴사 사유')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=100, verbose_name='장애 종류')),
                ('severity', models.CharField(choices=[('mild', '경증'), ('severe', '중증')], max_length=10, verbose_name='장애 중증도')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('high_school', '고등학교'), ('junior_college', '대학교 (2-3년제)'), ('university', '대학교 (4년제)'), ('master', '석사'), ('doctorate', '박사')], max_length=20, verbose_name='학교 종류')),
                ('school_name', models.CharField(max_length=100, verbose_name='학교명')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='전공명')),
                ('status', models.CharField(choices=[('attending', '재학중'), ('graduated', '졸업'), ('completed', '수료'), ('dropout', '중퇴')], max_length=20, verbose_name='재학 여부')),
                ('admission_date', models.CharField(max_length=7, verbose_name='입학일 (YYYY-MM)')),
                ('graduation_date', models.CharField(blank=True, max_length=7, null=True, verbose_name='졸업일 (YYYY-MM)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('served', '군필'), ('not_served', '미필'), ('exempted', '면제'), ('serving', '복무중')], max_length=20, verbose_name='복무 상태')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patriot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patriot_code', models.CharField(help_text='보훈 대상자일 경우 해당 코드를 입력합니다.', max_length=50, verbose_name='보훈 코드')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patriot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='관심 직무')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job_title')},
            },
        ),
    ]
