# Generated by Django 5.2.5 on 2025-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[('associate', '전문학사'), ('bachelor', '학사'), ('master', '석사'), ('doctorate', '박사')], max_length=50, null=True, verbose_name='학위'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='전공명'),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='degree',
            field=models.CharField(blank=True, choices=[('associate', '전문학사'), ('bachelor', '학사'), ('master', '석사'), ('doctorate', '박사')], max_length=50, null=True, verbose_name='학위'),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='전공명'),
        ),
    ]
