# Generated by Django 5.2.5 on 2025-09-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_education_degree_alter_education_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='task',
            field=models.TextField(blank=True, verbose_name='담당 업무'),
        ),
        migrations.AddField(
            model_name='resumecareer',
            name='task',
            field=models.TextField(blank=True, verbose_name='담당 업무'),
        ),
    ]
