# Generated by Django 5.2.5 on 2025-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_career_disability_education_militaryservice_patriot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='jobinterest',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='jobinterest',
            unique_together={('user', 'job_title')},
        ),
        migrations.AddField(
            model_name='career',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disability',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinterest',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('user', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='disability',
            unique_together={('user', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('user', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='jobinterest',
            unique_together={('user', 'job_title'), ('user', 'order')},
        ),
    ]
