# Generated by Django 5.2.5 on 2025-09-10 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_career_task_resumecareer_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('jd_context', models.TextField(blank=True, default='')),
                ('resume_context', models.TextField(blank=True, default='')),
                ('ncs_query', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('report_id', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate'), ('system', 'System')], max_length=16)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='api.interviewsession')),
            ],
            options={
                'db_table': 'interview_turn',
                'ordering': ['turn_index'],
                'unique_together': {('session', 'turn_index')},
            },
        ),
    ]
