# Generated by Django 5.2.5 on 2025-09-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_career_options_alter_disability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='admission_date',
            field=models.DateField(verbose_name='입학일'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='졸업일'),
        ),
    ]
