# Generated by Django 5.2.5 on 2025-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interviewsession_interviewturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='language',
            field=models.CharField(default='ko', max_length=8),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='followups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
