# Generated by Django 5.2.5 on 2025-09-05 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_education_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinterest',
            options={'ordering': ['order'], 'verbose_name': '관심 직무', 'verbose_name_plural': '관심 직무 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='jobinterest',
            unique_together={('user', 'order')},
        ),
        migrations.AlterField(
            model_name='education',
            name='admission_date',
            field=models.DateField(verbose_name='입학일 (YYYY-MM)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='졸업일 (YYYY-MM)'),
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='자기소개서 제목', max_length=100)),
                ('content', models.TextField(help_text='자기소개서 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('user', models.ForeignKey(help_text='자기소개서 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자기소개서',
                'verbose_name_plural': '자기소개서',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='이력서 제목 (예: 백엔드 개발자 지원용)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='최종 수정 일시')),
                ('user', models.ForeignKey(help_text='이력서 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '이력서',
                'verbose_name_plural': '이력서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='수상 또는 자격증명', max_length=100)),
                ('issuer', models.CharField(help_text='발급 기관', max_length=100)),
                ('date_awarded', models.DateField(help_text='취득일')),
                ('resume', models.ForeignKey(help_text='수상 내역이 포함된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='api.resume')),
            ],
            options={
                'verbose_name': '이력서 수상/자격증',
                'verbose_name_plural': '이력서 수상/자격증 목록',
                'ordering': ['-date_awarded'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='회사명', max_length=100)),
                ('department', models.CharField(help_text='부서명', max_length=100)),
                ('role', models.CharField(help_text='직책 (예: 팀장, 팀원)', max_length=100)),
                ('start_date', models.DateField(help_text='입사일')),
                ('end_date', models.DateField(blank=True, help_text='퇴사일', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='현재 재직중 여부')),
                ('responsibilities', models.TextField(help_text='담당 직무 및 성과')),
                ('resume', models.ForeignKey(help_text='경력 사항이 포함된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='api.resume')),
            ],
            options={
                'verbose_name': '이력서 경력',
                'verbose_name_plural': '이력서 경력 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='학교명', max_length=100)),
                ('major', models.CharField(help_text='전공', max_length=100)),
                ('degree', models.CharField(help_text='학위 (예: 학사, 석사)', max_length=50)),
                ('start_date', models.DateField(help_text='입학일')),
                ('end_date', models.DateField(blank=True, help_text='졸업일', null=True)),
                ('courses_taken', models.TextField(blank=True, help_text='이수 과목 또는 연구 내용')),
                ('resume', models.ForeignKey(help_text='학력 사항이 포함된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='api.resume')),
            ],
            options={
                'verbose_name': '이력서 학력',
                'verbose_name_plural': '이력서 학력 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='언어명 (예: English)', max_length=50)),
                ('proficiency', models.CharField(help_text='구사 수준 (예: Native, Fluent)', max_length=50)),
                ('resume', models.ForeignKey(help_text='외국어 능력이 포함된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.resume')),
            ],
            options={
                'verbose_name': '이력서 외국어',
                'verbose_name_plural': '이력서 외국어 목록',
            },
        ),
        migrations.CreateModel(
            name='ResumeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='링크 제목 (예: GitHub, 포트폴리오)', max_length=100)),
                ('url', models.URLField(help_text='링크 주소')),
                ('resume', models.ForeignKey(help_text='링크가 포함된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.resume')),
            ],
            options={
                'verbose_name': '이력서 링크',
                'verbose_name_plural': '이력서 링크 목록',
            },
        ),
    ]
