# Generated by Django 5.2.5 on 2025-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_interviewsession_context_interviewsession_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewturn',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(db_index=True, default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='language',
            field=models.CharField(db_index=True, default='ko', max_length=8),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='role',
            field=models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate'), ('system', 'System')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='turn_index',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['status', 'started_at'], name='interview_s_status_4d0801_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewturn',
            index=models.Index(fields=['session', 'turn_index'], name='interview_t_session_40a6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewturn',
            constraint=models.UniqueConstraint(fields=('session', 'turn_index'), name='unique_session_turnindex'),
        ),
    ]
