# Generated by Django 5.2.6 on 2025-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_interviewturn_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='rag_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
