# Generated by Django 5.2.6 on 2025-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_interviewsession_rag_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='interviewer_mode',
            field=models.CharField(choices=[('team_lead', 'Team Lead'), ('executive', 'Executive')], db_index=True, default='team_lead', max_length=20, verbose_name='면접관 모드'),
        ),
    ]
