# Generated by Django 5.2.6 on 2025-09-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_interviewsession_interviewer_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interviewturn',
            name='unique_session_turnindex',
        ),
        migrations.RemoveIndex(
            model_name='interviewturn',
            name='interview_t_session_40a6fa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='interviewturn',
            unique_together={('session', 'turn_index')},
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='turn_label',
            field=models.CharField(default='0', help_text="사용자에게 보여질 순번 (예: '1', '1-1')", max_length=10),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='role',
            field=models.CharField(choices=[('INTERVIEWER', '면접관'), ('CANDIDATE', '지원자')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='turn_index',
            field=models.PositiveIntegerField(help_text='내부 정렬을 위한 숫자 인덱스'),
        ),
        migrations.AlterModelTable(
            name='interviewturn',
            table=None,
        ),
        migrations.RemoveField(
            model_name='interviewturn',
            name='followups',
        ),
    ]
