# Generated by Django 5.2.6 on 2025-09-21 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_interviewturn_unique_session_turnindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jd_context', models.TextField(blank=True, help_text='정제된 JD 텍스트')),
                ('resume_context', models.TextField(blank=True, help_text='정제된 이력서 텍스트')),
                ('research_context', models.TextField(blank=True, help_text='정제된 리서치 자료 텍스트')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
