# Generated by Django 5.2.6 on 2025-09-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewturn',
            name='question_ssml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
